const en={
    welcome:"Hello",
    SanoTimer:"SanoTimer",
    connect:"Connect Applications..",
    descOne:"Please write passwords to connect systems",
    connectButton:"Connect Devices",
    explanation:"irrigation systems",
    appMode:"Application Modes",
    reset:"Reset",
    mannual:"Mannual Mode",
    test:"Test Mode",
    Settings:"Settings",
    inc:"İncrement",
    save:"Save It!",
    goBack:"Go Back",
    detail:"Program İnformaiton",
    addProgram:"Add New Program",
    day:"Day",
    controller:"Controller",
    start:"Start time",
    stop: "Stop time",
    valf: "Valve",
    yes:"Evet",
    cancel:"İptal",
    Que:"Sistemde kayıtlı tüm bilgiler silinecek emin misniz ?",
    proName:"Program ismi",



};
const tr={
    welcome:"Merhaba",
    SanoTimer:"SanoTimer",
    connect:" Uygulamaya Bağlan ..",
    descOne:"Sisteme giriş yapmak için şifreyi giriniz..",
    connectButton:"Bağlan",
    explanation:"Sulama Sistemleri",
    appMode:"Uygulama Modları",
    reset:"Sıfırla",
    mannual:"Manuel Mod",
    test:"Test Modu",
    Settings:"Ayarlar",
    inc:"Artır",
    save:"Kaydet!",
    goBack:"Geri dön",
    detail:"Program Bilgileri",
    addProgram:"Program Ekle",
    day:"Gün",
    controller:"Kontrolcü",
    start:"Başlangıç zamanı",
    stop: "Bitiş zamanı",
    valf: "Valf",
    yes:"Yes",
    cancel:"Cancel",
    Que:"Are you sure you want to delete the programs that have been saved in the system? ",
    proName:"Program Name",
};

export {en,tr};